# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];
  boot.resumeDevice = "/dev/disk/by-uuid/6e41e996-1c8c-4a01-bf15-d90fd53528b5";
  boot.kernelParams = ["resume_offset=272384"];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/6e41e996-1c8c-4a01-bf15-d90fd53528b5";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E2A4-62F0";
    fsType = "vfat";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/85e13df9-02e1-4aff-8384-3a5fd4f9d75d";
    fsType = "ext4";
  };

  fileSystems."/home/mihranmashhud/Data" = {
    device = "/dev/disk/by-uuid/ff386612-8c1b-444a-b8fe-a43e428ad61d";
    fsType = "ext4";
  };

  fileSystems."/var/lib/libvirt/images" = {
    device = "/dev/disk/by-uuid/5758bc2e-f6ba-4346-a691-15cff3c1d27f";
    fsType = "ext4";
  };

  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 32 * 1024;
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
